modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="tutorialmod"
version="1.0"
displayName="Tutorial Mod"
logoFile="logo.png"
credits=""
authors="TurtyWurty"
description='''
A tutorial mod for Minecraft 1.18!

beans
'''